project_id = "mkfaphusizsjgcpkepld"

[functions.jotform-webhook]
verify_jwt = false

[functions.bulk-import-policies]
verify_jwt = true

[functions.setup-email-cron]
verify_jwt = true

[functions.run-policy-reminder]
verify_jwt = true

[functions.export-ezlynx]
verify_jwt = true
